### ISSUE TITLE
problems with 'npm start'

### ISSUE THREAD

**Issue by starstaysky** [luventa/vue-koa-boilerplate#1]
npm start 
Couldn't find preset "env" relative to directory "/Users/fuxing/Desktop/my project"

**Comment by luventa** [comment]
Hi starstaysky, I think it's caused by missing module `babel-preset-env`.
Pls execute the command below:

```bash
npm install babel-preset-env --save-dev
```
or if you are using `yarn`
```bash
yarn add babel-preset-env --dev
```
